# Generated by Django 4.1.5 on 2023-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Home", "0002_alter_contact_phone")]

    operations = [
        migrations.AlterField(
            model_name="contact", name="phone", field=models.CharField(max_length=20)
        )
    ]
